name: Build and Deploy Backend via FTP

on:
  push:
    branches:
      - test  # Déclenche le workflow sur la branche 'test'
      - main  # Déclenche le workflow sur la branche 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        working-directory: .  # Assure l'installation au bon endroit
        run: npm install

      - name: Run Lint
        working-directory: .  # Vérifie le code
        run: npm run lint
        continue-on-error: false  # Stoppe si erreur

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        working-directory: .  # Assure l'installation au bon endroit
        run: npm install

      - name: Run Test
        working-directory: .  # Vérifie le code
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: lint  # Attend que `build` soit terminé avant de commencer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        working-directory: .  # Assure l'installation au bon endroit
        run: npm install

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}       # Adresse du serveur FTP
          username: ${{ secrets.FTP_USER }}     # Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASS }}     # Mot de passe FTP
          protocol: ftps                        # Utilisation de FTPS pour plus de sécurité
          port: 21                              # Port FTP par défaut
          server-dir: www/backend/              # Dossier distant où déployer le contenu